apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "chart.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "chart.fullname" . }}-serving-cert
  labels:
  {{- include "chart.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "chart.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-v1-buildconfig
  failurePolicy: Fail
  name: buildconfig.dana.io
  rules:
  - apiGroups:
    - build.openshift.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - buildconfigs
  sideEffects: NoneOnDryRun