apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-sns
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - dana.hns.io
  resources:
  - subnamespaces
  verbs:
  - create
  - list
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - delete
- apiGroups:
  - project.openshift.io
  resources:
  - projects
  verbs:
  - delete
- apiGroups:
  - dana.hns.io
  resources:
  - updatequota
  verbs:
  - create
  - update
  - list
  - get
  - patch