kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sns
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
rules:
  - verbs:
      - create
      - list
      - get
    apiGroups:
      - dana.hns.io
    resources:
      - subnamespaces
  - verbs:
      - delete
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - delete
    apiGroups:
      - project.openshift.io
    resources:
      - projects
  - verbs:
      - create
      - update
      - list
      - get
      - patch
    apiGroups:
      - dana.hns.io
    resources:
      - updatequota
