kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: impersonate
  namespace: sns-system
rules:
  - verbs:
      - impersonate
    apiGroups:
      - ''
    resources:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: impersonate
  namespace: sns-system
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sns-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: impersonate

