resources:
- admin_sns.yaml
- auth_proxy_client_clusterrole.yaml
- auth_proxy_role_binding.yaml
- auth_proxy_role.yaml
- auth_proxy_service.yaml
- leader_election_role_binding.yaml
- leader_election_role.yaml
- role_binding.yaml
- role.yaml
- service_account.yaml
- subnamespace_editor_role.yaml
- subnamespace_viewer_role.yaml