apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.limitRange.name }}
  labels:
  {{- include "hns.labels" . | nindent 4 }}
data:
  limitRangeDefaults: {{ .Values.config.limitRange.defaults | toYaml | indent 1 }}