{{if .Values.monitoring.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hns.fullname" . }}-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "hns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.monitoring.service.type }}
  ports:
  - name: https
    port: {{ .Values.monitoring.service.port }}
    protocol: {{ .Values.monitoring.service.protocol }}
    targetPort: {{ .Values.monitoring.service.targetPort }}
  selector:
    control-plane: controller-manager
{{end}}