apiVersion: v1
kind: Service
metadata:
  name: {{ include "hns.fullname" . }}-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "hns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: {{ .Values.service.httpsPort }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    control-plane: controller-manager