apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.observedResources.name }}
  labels:
  {{- include "hns.labels" . | nindent 4 }}
data:
  resources: {{ join "," .Values.config.observedResources.resources }}