apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hns.fullname" . }}-prometheus-k8s-role
  labels:
  {{- include "hns.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - services
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch