apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "hns.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "hns.fullname" . }}-serving-cert
  labels:
  {{- include "hns.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "hns.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-v1-migrationhierarchy
  failurePolicy: Fail
  name: migrationhierarchy.dana.io
  rules:
  - apiGroups:
    - dana.hns.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - migrationhierarchies
  sideEffects: NoneOnDryRun
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "hns.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-v1-namespace
  failurePolicy: Fail
  name: namespace.dana.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - namespaces
  sideEffects: NoneOnDryRun
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "hns.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-v1-rolebinding
  failurePolicy: Fail
  name: rolebinding.dana.io
  rules:
  - apiGroups:
    - rbac.authorization.k8s.io
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - rolebindings
  sideEffects: NoneOnDryRun
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "hns.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-v1-subnamespace
  failurePolicy: Fail
  name: subnamespace.dana.io
  rules:
  - apiGroups:
    - dana.hns.io
    apiVersions:
    - v1
    operations:
    - DELETE
    - CREATE
    - UPDATE
    resources:
    - subnamespaces
  sideEffects: NoneOnDryRun
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "hns.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-v1-updatequota
  failurePolicy: Fail
  name: updatequota.dana.io
  rules:
  - apiGroups:
    - dana.hns.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - updatequota
  sideEffects: NoneOnDryRun