apiVersion: v1
kind: Service
metadata:
  name: {{ include "hns.fullname" . }}-webhook-service
  labels:
  {{- include "hns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  ports:
    - port: {{ .Values.webhookService.ports.port }}
      protocol: {{ .Values.webhookService.ports.protocol }}
      targetPort: {{ .Values.webhookService.ports.targetPort }}
  selector:
    control-plane: controller-manager