name: Pre Merge E2E test

on:
  pull_request:
    branches:
      - ci
    types: [opened, reopened, synchronize]
jobs:
  e2e-tests:
    name: E2e-tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      REGISTRY: ghcr.io
      REPOSITORY_NAME: ${{ github.repository }}
      DANA_ORG: dana-team
    steps:
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.HNS_CI_CLUSTER }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Go Vet
        run: go vet ./...
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Add IMAGE_TAG env property with commit short sha
        run: echo "IMAGE_TAG=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build and push docker image
        run: make docker-build docker-push IMG=${{ env.REGISTRY }}/dana-team/${{ env.REPOSITORY_NAME }}:${IMAGE_TAG}
      - name: Deploy hns
        run: make install deploy IMG=${{ env.REGISTRY }}/dana-team/${{ env.REPOSITORY_NAME }}:${IMAGE_TAG}
      - name: test
        run: make test-e2e
