name: Pre Merge E2E test

on:
  pull_request:
    branches:
      - ci
    types: [opened, reopened, synchronize]
jobs:
  e2e-tests:
    name: E2e-tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      REGISTRY: ghcr.io
      REPOSITORY_NAME: ${{ github.repository }}
      DANA_ORG: dana-team
    steps:
      - name: auth
        uses: mobiledevops/secret-to-file-action@v1
        with:
          base64-encoded-secret: ${{ secrets.HNS_CI_CLUSTER }}
          filename: "config"
          working-directory: "~/.kube"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Go Vet
        run: go vet ./...
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        run: make docker-build docker-push IMG=${{ env.REGISTRY }}/dana-team/${{ env.REPOSITORY_NAME }}:${GITHUB_REF##*/}
      - name: test
        run: make test
